### ISSUE TITLE
Regarding PyMoe

### ISSUE THREAD

**Issue by ccubed** [AIIX/animelist-skill#1]
I have an issue with you copying entire pieces of my code, slapping them into your project and then taking sole credit for writing the code. Starting on line 44 of your code (https://github.com/AIIX/animelist-skill/blob/master/__init__.py#L44) and up to line 76 you have copied everything from my Anilist code starting at line 68 in my file (https://github.com/ccubed/PyMoe/blob/master/Pymoe/Anilist/search.py#L68) and up to line 100 with only minimal changes. I also saw that you created a fork (12:36 AM EST) and then deleted it, I suppose to gather the code necessary to paste here and change it slightly to fit your purposes. If you want to copy my code wholesale, then at least mention my project, or me, as your source.

**Comment by AIIX** [comment]
Apologies, was trying to build PyMoe with python 2 but it seems its only python 3 compatible and wanted to use PyMoe directly but was unable to due to the above. Credits to your git account and code have been added. If you need any other changes to this let me know. Closing Issue for now.
